spring:
  datasource:
   url: jdbc:postgresql://localhost:5432/online_video_training
   username: postgres
   password: Lyhour24
  jpa:
   properties:
    hibernate:
    dialect: org.hibernate.dialect.PostgreSQLDialect
    globally_quoted_identifiers: true
   hibernate:
    ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    servlet:
      load-on-startup: 1
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml